server:
  port: 8080
spring:
  profiles:
    active: local
---
vogeez:
  authorization-service:
    oauth2.issuer: https://dev.accounts.vogeez.net
spring:
  mail:
    username: test@gmail.com
    password: test
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/authentication;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: dev
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: prod